root: true

globals:
  console: false
  window: false

rules:
  new-cap: "off"
  valid-jsdoc: "off"
  import/newline-after-import: "off"
  import/first: "off"

parserOptions:
  ecmaVersion: 2017
  sourceType: "module"

overrides:
  - files: src/*
    parser: "babel-eslint"
    rules:
      # To reduce size for babel-translation.
      no-restricted-syntax:
        - error
        - ClassDeclaration
        - ClassExpression
        - ForOfStatement
      prefer-rest-params: "off"
      prefer-spread: "off"
